config:
  backup: true
  banner: true
  create: true
  diff_command: diff -r -u --color=auto {0} {1}
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  template_dotfile_default: true
  workdir: ~/.config/workdir
dotfiles:
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_aliases:
    src: bash/bash_aliases
    dst: ~/.bash_aliases
  f_bash_profile:
    src: bash/bash_profile
    dst: ~/.bash_profile
  f_bash_env:
    src: bash/bash_env
    dst: ~/.bash_env
  f_gitconfig:
    src: src/git/dotfiles/git/gitconfig
    dst: ~/.gitconfig
    chmod: '755'
profiles:
  devoid:
    dotfiles:
    - f_bashrc
    - f_bash_aliases
    - f_bash_profile
    - f_bash_env
    - f_gitconfig
