# Regular ZSH Theme

# Font
POWERLEVEL9K_MODE="nerdfont-complete"

# Prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
if [[ $(whoami | tr -d '\n') == 'root' ]]; then
	POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{red}╭─%f"
	POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{red}╰─⮞%f "
else
	POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{green}╭─%f"
	POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{green}╰─⮞%f "
fi

# Separators
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="\ue238"

# Root indicator
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="052"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="009"

# OS Segment
POWERLEVEL9K_OS_ICON_BACKGROUND='234'
POWERLEVEL9K_LINUX_ICON='%F{cyan}\uf303 %B%F{255}arch%b%F{cyan}linux%f'

# Context
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='208'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='234'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='196'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='234'
DEFAULT_USER='devon'
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%B%n%b"

# Directory
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_DIR_HOME_FOREGROUND='018'
POWERLEVEL9K_DIR_HOME_BACKGROUND='039'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='018'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='039'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='208'
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='052'
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='009'

# Status
POWERLEVEL9K_CARRIAGE_RETURN_ICON="\uf12a"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='052'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='009'
POWERLEVEL9K_STATUS_OK_FOREGROUND='040'
POWERLEVEL9K_STATUS_OK_BACKGROUND='234'

# Background jobs
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='190'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='238'

# Time
POWERLEVEL9K_TIME_FORMAT="%F{black}\uf017 %D{%I:%M}%f"
POWERLEVEL9K_TIME_FOREGROUND="gray"
POWERLEVEL9K_TIME_BACKGROUND
